/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "var(--color-on-background)",
        "primary": "var(--color-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-error": "var(--color-on-error)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "tertiary": "var(--color-tertiary)",
        "surface-tint": "var(--color-surface-tint)",
        "error": "var(--color-error)",
        "on-tertiary": "var(--color-on-tertiary)",
        "error-container": "var(--color-error-container)",
        "background": "var(--color-background)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "secondary": "var(--color-secondary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface": "var(--color-surface)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "outline": "var(--color-outline)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "2xl": "64px",
        "3xl": "80px",
        "4xl": "120px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
