/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e4e1e9",
        "primary": "#adc6ff",
        "secondary-container": "#0267b8",
        "on-tertiary-fixed": "#311400",
        "on-secondary-fixed-variant": "#004883",
        "on-tertiary-fixed-variant": "#723600",
        "tertiary-fixed-dim": "#ffb786",
        "surface-bright": "#39383e",
        "secondary-fixed": "#d4e3ff",
        "surface-dim": "#131318",
        "surface-container-lowest": "#0e0e13",
        "on-error": "#690005",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed": "#001a42",
        "outline-variant": "#424754",
        "on-surface-variant": "#c2c6d6",
        "surface-container-highest": "#35343a",
        "secondary-fixed-dim": "#a4c9ff",
        "on-primary-fixed-variant": "#004395",
        "tertiary": "#ffb786",
        "surface-tint": "#adc6ff",
        "error": "#ffb4ab",
        "on-tertiary": "#502400",
        "error-container": "#93000a",
        "background": "#131318",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#e4e1e9",
        "surface-variant": "#35343a",
        "surface-container": "#1f1f25",
        "secondary": "#a4c9ff",
        "on-tertiary-container": "#461f00",
        "on-primary": "#002e6a",
        "surface-container-low": "#1b1b20",
        "inverse-on-surface": "#303036",
        "inverse-primary": "#005ac2",
        "surface": "#131318",
        "inverse-surface": "#e4e1e9",
        "on-secondary-container": "#d6e5ff",
        "on-secondary-fixed": "#001c39",
        "on-secondary": "#00315d",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#00285d",
        "tertiary-container": "#df7412",
        "outline": "#8c909f",
        "primary-container": "#4d8eff",
        "surface-container-high": "#2a292f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "2xl": "64px",
        "3xl": "80px",
        "4xl": "120px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
